@baseurl=https://localhost:7269
@Usertoken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0QHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkpvaG4gRG9lIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiT3duZXIiLCJleHAiOjE2ODQyMzQxMjcsImlzcyI6Imh0dHA6Ly9mYXN0Zm9vZGFwaS5jb20iLCJhdWQiOiJodHRwOi8vZmFzdGZvb2RhcGkuY29tIn0.E-FIQg51NeQG3zULht8V-UOUqGwgzOuvCFWv9mdkSwc
@Admintoken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0YWRtaW5AdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5Vc2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE2ODQyMzc5ODgsImlzcyI6Imh0dHA6Ly9mYXN0Zm9vZGFwaS5jb20iLCJhdWQiOiJodHRwOi8vZmFzdGZvb2RhcGkuY29tIn0.R_2-lt82MpzrgWqzcjb155y4el15HZdVglSvG9UDspA

GET {{baseurl}}/api/restaurant?PageNumber=1&PageSize=15

###
POST {{baseurl}}/api/restaurant/1/order
Authorization: Bearer {{Usertoken}}
###



###

POST {{baseurl}}/api/account/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testP$$w0rd",
  "confirmPassword": "testP$$w0rd",
  "name": "John Doe"
}

###

POST {{baseurl}}/api/account/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testP$$w0rd"
}
###
POST {{baseurl}}/api/account/login
Content-Type: application/json

{
  "email": "testadmin@test.com",
  "password": "TestAdminP@$$w0rd"
}
###

PUT {{baseurl}}/api/account
Content-Type: application/json
Authorization: Bearer {{Usertoken}}

{
  "name": "John Doe",
  "dateofBirth": "1990-01-21T10:58:09.365Z",
  "contactNumber": "+48990420567",
  "country": "Poland",
  "city": "Kraków",
  "street": "Warszawska",
  "apartmentNumber": "10/5"
}

###

POST {{baseurl}}/api/restaurant
Content-Type application/json
Authorization: Bearer {{Usertoken}}

{
  "name": "McDonald",
  "description": "Ronald McDonald's restaurants",
  "contactNumber": "+48990420567",
  "email": "mcdonald@test.com",
  "country": "USA",
  "city": "New York",
  "street": "Millwind Street",
  "apartmentNumber": "10"
}
###

GET {{baseurl}}/api/restaurant/1 

###

DELETE {{baseurl}}/api/restaurant/1
Authorization: Bearer {{Admintoken}}

###

DELETE {{baseurl}}/api/account
Content-Type application/json

{
  "email": "test@test.com",
  "password": "testP$$w0rd"
}

###
POST {{baseurl}}/api/specialDiet
Content-Type application/json
Authorization: Bearer {{Admintoken}}

{
  "name": "Vegetarian",
  "description": "Diet where you dont eat meat"
}

###

GET {{baseurl}}/api/specialDiet/1

###

GET {{baseurl}}/api/specialDiet?PageNumber=1&PageSize=15

###

PUT {{baseurl}}/api/specialDiet/1
Content-Type application/json
Authorization: Bearer {{Admintoken}}

{
     "name": "Vege",
     "description": "Diet where you dont eat meat and animal products"
}

###

DELETE {{baseurl}}/api/specialDiet/2
Authorization: Bearer {{Admintoken}}

###

POST {{baseurl}}/api/restaurant/1/dish
Authorization: Bearer {{Usertoken}}
Content-Type application/json

{
  "name": "BigMac",
  "description": "Well known McDonalds Burger",
  "basePrize": 10.00,
  "baseCaloricValue": 1000,
  "allowedCustomization": true,
  "isAvilable": true
}

###

GET {{baseurl}}/api/dish/1

###

GET {{baseurl}}/api/restaurant/1/dish?PageNumber=1&PageSize=15

###
Post {{baseurl}}/api/dish/1/ingredient
Authorization: Bearer {{Admintoken}}
Content-Type application/json

{
    "name": "Bu³ka",
  "description": "Pieczywo",
  "prize": 100,
  "isRequired": false
}
###
PUT {{baseurl}}/api/dish/1
Content-Type application/json
Authorization: Bearer {{Usertoken}}

{
  "name": "BigMac",
  "description": "Well known McDonalds Burger",
  "basePrize": 15.00,
  "baseCaloricValue": 1000,
  "allowedCustomization": true,
  "isAvilable": true
}
###